### ISSUE TITLE
Promote WTT responsiveness league table on TWFY MP pages

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#1098]

**Comment by wrightmartin** [comment]
I've ben searching through the TWFY sass for some existing styles but can't find anything, but I'm sure we've done something similar before. Any ideas @zarino @dracos?

Otherwise, something like this?

![screen shot 2016-05-16 at 11 00 52](https://cloud.githubusercontent.com/assets/2292925/15286519/7ac5940a-1b55-11e6-8587-82bc199ccde0.png)

**Comment by zarino** [comment]
Oooh, funky! I like it.

Don't know why, but I'd be interested in seeing it positioned as *just another thing* in the main content column, with a link in the sidebar nav – rather than it being a special case full-width element. After all, I could easily imagine "Responsiveness" as a section on an MP’s profile, just like "Votes" and "Appearances". It's a thing an MP does.

**Comment by zarino** [comment]
PR here: https://github.com/mysociety/theyworkforyou/pull/1103

Needs some dev work, to pull through the latest data.

**Comment by MyfanwyNixon** [comment]
Where are we at with this, please? @JenMysoc does a dev need to be assigned?

**Comment by JenMysoc** [comment]
Struan did the work on this pull request so we need someone not on our team
to review - @dracos probably

**Comment by dracos** [comment]
Not sure why it needs someone not on the team to review it, but done :)
