### ISSUE TITLE
Links to source (Hansard website) missing

### ISSUE THREAD

**Issue by gwire** [mysociety/theyworkforyou#1108]
Speeches seem to be missing their Hansard/etc source links.

Example [this speech](http://www.theyworkforyou.com/whall/?id=2016-06-15a.385.0) currently does not contain a source, so I assume something has broken for [_section_content.php](https://github.com/mysociety/theyworkforyou/blob/08576a370010e2b3546a963ff18d742b36c6d218/www/includes/easyparliament/templates/html/section/_section_content.php).

```html
<ul class="debate-speech__meta debate-speech__links">
      <li class="link-to-speech">
         <span class="link-to-speech__label">Link to this speech</span>
         <a href="/whall/?id=2016-06-15a.385.0#g385.1" class="link debate-speech__meta__link">In context</a>
         <a href="/whall/?id=2016-06-15a.385.1" class="link debate-speech__meta__link">Individually</a>
      </li>
 </ul>
```

**Comment by dracos** [comment]
This issue is mentioned in our parser repository at https://github.com/mysociety/parlparse/issues/50 – the XML we now get from parliament does not include any source links, so we are unable to provide them.

**Comment by dracos** [comment]
Or rather, it does include source links but they are of the form `/pa/cm201617/cmhansrd/cm160615/debtext/160615-0001.htm#16061533000007` which no longer work since parliament switched to their new Hansard site.

**Comment by gwire** [comment]
There's enough data there to construct a useful link in the interim though?

Does the new xml feed contain the Volume and Column numbers? For the speech above I can see that it's column 385, so I can construct a link
```
https://hansard.parliament.uk/search/column/?VolumeNumber=611&ColumnNumber=385WH
```
which will produce a `302` redirect to 
```
https://hansard.parliament.uk/commons/2016-06-15/debates/16061526000002/WestminsterHall#385WH
```

**Comment by RichardTaylor** [comment]
If this might not be fixed by Hansard soon how about a vaguer "source" link towards the bottom of a page, pointing to eg. 

https://hansard.parliament.uk/

or the relevant date

https://hansard.parliament.uk/Commons/2016-06-07

**Comment by MyfanwyNixon** [comment]
> I’m a journalist and use your website reasonably often.

> I’m sure there used to be a ‘link to Hansard source’ thing next to various speeches but I can’t see it anywhere now. Has this been removed now?

**Comment by MyfanwyNixon** [comment]
> Immensely irritating that you have removed Hansard column numbers (and links) – absolutely standard way of referencing speeches in Parliament.

**Comment by DavidJFPollock** [comment]
It's now four months since this problem arose - what are you doing about it?

**Comment by dracos** [comment]
Hi @DavidJFPollock, and thanks for your comment. As I wrote above, and in the linked ticket, the issue with linking to the source transcript is that the source data we use for TheyWorkForYou does not include source links any more (or rather, as explained at https://github.com/mysociety/theyworkforyou/issues/1108#issuecomment-226763968, they include non-working broken links). Fundamentally the issue is that Parliament is not including working source links and the onus is really on them to include them; please feel free to let them know that they should include working source links in their data.

Of course, as you note, it's been a while and they haven't yet done anything; I imagine they have many other things to do, and I and others have discussed, as you can read, possible workarounds and limited solutions that would not fully fix the problem. TheyWorkForYou is run by a charity with limited resources and many demands on our time. All the code for TheyWorkForYou and the parlparse parser (https://github.com/mysociety/parlparse) is open source and if the issue is one that means a lot to you, perhaps you have the time or resources to help contribute to fixing this issue yourself. The ticket at https://github.com/mysociety/parlparse/issues/50 includes a suggested plan of attack to try and construct the source URLs ourselves, for example, which would probably be the best way to go.

There may be two separate issues here, though – it's possible we should be able to put back the citation reference (date and column number), even if we don't have a source link to show, which might have been missed in the main issue of this ticket. I have opened a separate ticket for that at #1179 – again, if you were able to work out what needs to change to effect that, please feel free, otherwise it feels like a much easier issue and we will hopefully be able to look at it in the near future.

**Comment by DavidJFPollock** [comment]
Thanks for your very rapid reply.  I'm sorry, I have no technical expertise in this area.  Do you have an address for whoever is responsible at Hansard?

**Comment by RichardTaylor** [comment]
I'm surprised this issue is closed given its still an issue from the point of view of users of TheyWorkForYou. 

I've made a comment / suggestion for improving the situation at: 

https://github.com/mysociety/parlparse/issues/50#issuecomment-1059122907

**Comment by andylolz** [comment]
@gwire’s proposed solution (https://github.com/mysociety/theyworkforyou/issues/1108#issuecomment-226772608) is cool and useful. But I’m not sure how doable it is using parlparse data, because parlparse data doesn’t appear to include the series number or volume number ([see for example](https://www.theyworkforyou.com/pwdata/scrapedxml/westminhall/westminster2016-06-15a.xml)). And of course it’s still not quite as good as a direct link to the speech.
