### ISSUE TITLE
Result of a single deferred division presented without context

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1109]
At:
http://www.theyworkforyou.com/debates/?id=2016-04-13c.474.0#g482.0

the results of a [deferred division](http://www.parliament.uk/site-information/glossary/deferred-divisions/) are presented without any text explaining what the division is about, either before or after the list of voting MPs.

I've added an annotation linking to [Hansard's description of the vote](https://hansard.parliament.uk/Commons/2016-04-13/division/16041344001946/EmploymentAgenciesEtc?outputType=Names). 

There doesn't appear to be a consistent problem. There's a very nicely presented, more recent, deferred division shown at:

http://www.theyworkforyou.com/debates/?id=2016-06-15a.1879.1&s=deferred

I've not seen any other similar problems.

Is it worth checking if this is an omission in the source material, or if the source material has changed since it was obtained?

If it is a one-off and a problem with the source material my annotation can be considered to fix and close this.

**Comment by dracos** [comment]
The 2016-04-13 source data puts the headings inside the `<Division>` element, where they are being missed, the 2016-06-15 source has the headings before the division. This is a symptom of mysociety/parlparse#54, in that the parser should be alerting or erroring when it finds content it has failed to parse rather than silently dropping it as it currently is doing.

**Comment by dracos** [comment]
http://www.theyworkforyou.com/debates/?id=2016-04-13c.482.1 is slightly better now (heading issue present, but meh), parser should now spot/handle anything in a Division a bit better.
