### ISSUE TITLE
Wording on fracking voting line

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1135]
A user writes:

> I'm writing out of concern about the way in which your site surfaces information about fracking votes. MPs who have taken a stance against fracking and voted against its expansion are reported as having "Generally voted against greater regulation of hydraulic fracturing (fracking) to extract shale gas". While technically true, this doesn't convey the fact that the regulation they have voted against allows for the expansion of the practice and gives a misleading impression that the MP is taking a pro-fracking approach. I have personally seen both Angela Eagle and Clive Lewis criticised for their votes on fracking by people who misunderstand the information conveyed on their TWFY pages.

> Would it be at all possible that the wording of your summary could be reworked? It seems like giving greater clarity would be the logical thing to do given the site's very admirable goal of making stances on issues easily comprehensible to as wide an audience as possible.

**Comment by RichardTaylor** [comment]
While I can imagine those reading the voting records might want to know if an MP is in favour of fracking, or if they oppose it, that's not something MPs have voted on. 

We can't determine from the voting record if an MP is for or against fracking. 

The votes have been on the degree of regulation. 

Those supporting more regulation might well claim to be very much in favour of fracking - arguing to get public support it needs to be done responsibly and safely; others supporting more regulation might be doing so because they don't really want it to happen at all. 


>the regulation they have voted against allows for the expansion of the practice 
I don't think that's the case; there are two votes which could be being referred to here:

1. http://www.publicwhip.org.uk/division.php?date=2015-12-16&number=151&mpn=Angela_Eagle&mpc=Wallasey&house=commons
Here the regulation Angela Eagle voted against sought to extend a ban on fracking in sensitive areas. 

2.  http://www.publicwhip.org.uk/division.php?date=2015-02-11&number=156&mpn=Angela_Eagle&mpc=Wallasey&house=commons
Here Angela Eagle voted  against requiring a more extensive set of conditions be met prior to fracking. 

Neither of those are votes against expanding fracking. 

I'll write to the correspondent. If we've got someone able and willing to improve the vote descriptions here, for example showing what would happen if the regulation mentioned at 1. wasn't passed, then that's excellent. I'll ask if they've got a specific proposal for a change.

**Comment by RichardTaylor** [comment]
The user never got back to us with any further comments so I'll close this. 

It raises the question of if we should say anything on fracking if we can't provide statements on simply 
"for fracking" / "against fracking".  

It think what we've got is better than nothing.

**Comment by RichardTaylor** [comment]
We've had correspondence from someone else on this subject.  The below is from my reply:

>You have mentioned the committee which considered the regulations. I presume you are referring to:

>http://www.publications.parliament.uk/pa/cm201516/cmgeneral/deleg2/151027/151027s01.htm

>There the minister states:

>>"The draft regulations serve to strengthen further the protections already in place for protected areas" 
>
>and
>
>> "The regulations tighten the protections on hydraulic fracturing"

>Those statements appear to be in-line with the description on PublicWhip and the way votes on the matter are taken into account when producing the statements on TheyWorkForYou.  A vote for the regulations is a vote for greater regulation of shale gas extraction.

>The descriptions on PublicWhip are not based on what the minister said in committee, but on the basis of the content of the regulations; in this case though both align.

>I understand an MP might vote against greater regulation of shale gas extraction on the grounds they want even tighter regulation than what is proposed however PublicWhip and TheyWorkForYou report how MPs actually vote and don't yet explicitly and directly include MPs explanations of their votes, though there are links to debates where such explanations may be found.

>I have added a link to the debate in committee in an annotation at:

>https://www.theyworkforyou.com/debates/?id=2015-12-16c.1671.1


> Hopefully that will help readers seeking to find out more about this subject.
