### ISSUE TITLE
Integrate support for Xapian replication

### ISSUE THREAD

**Issue by hazelesque** [mysociety/theyworkforyou#1167]
### Summary

Ticket to track work and PRs on TWFY relating to https://github.com/mysociety/sysadmin/issues/654

**Comment by hazelesque** [comment]
I've pushed my initial commits to the [1167-xapian-replication](https://github.com/mysociety/theyworkforyou/compare/1167-xapian-replication) feature branch.

These still need testing, but could @dracos and/or @struan take a look and see whether the approach looks sensible?

Additionally, we still need to decide whether to trigger the replication process from "morningupdate", or independently. The replication script requires a number of pieces of information to function correctly - perhaps these could go into the config file? (Any opinions?)

**Comment by hazelesque** [comment]
@dracos / @struan - ping?

**Comment by sagepe** [comment]
I've picked this up and made a slight change to add support for setting XAPIAN_MAX_CHANGESETS to `conf/general` and then checking and setting this if necessry within `search/index.pl` as this isn't always called from `scripts/morningupdate`.

I've created a new branch, and will open a PR.

**Comment by sagepe** [comment]
As discussed in https://github.com/mysociety/sysadmin/issues/654, rather than trigger the replication from cron a better option might be the `morningupdate` script.

Given the various bits of information needed and the fact that these are quite implementation specific it would seem sensible to make these configuration variables rather than include them in this repository (this is hinted at above in one of Hazel's comments).

Unless there are objections I'll add these as optional configuration variables in `conf/general` and update `morningupdate` at the same time as fixing the issues flagged by @dracos in the PR.

**Comment by struan** [comment]
Closed as of https://github.com/mysociety/theyworkforyou/commit/2980ca7546efd376d0be8bc066fc0e1f54352556
