### ISSUE TITLE
Cat Smith: offices are out of date

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1193]
Ms Smith has contacted us to say:

> A constituent has flagged for me that your offices held by me part of your bio for me needs updating. I’m no longer a Shadow Minister for Women and Equalities since June 2016.
> Also, since 1 November 2016 I have also held the post of Shadow Deputy Leader of the House of Commons.
> Thank you for your website, which I know my constituents find very useful.

**Comment by dracos** [comment]
On https://www.theyworkforyou.com/mp/25432/cat_smith/lancaster_and_fleetwood we do list Shadow Deputy Leader of the House of Commons, and a Junior Shadow Minister for Women and Equalities that ended in June 2016, so those are okay. There is a spurious Shadow Minister for Women and Equalities which should not be present, and it appears to be there because Parliament changed the post from Shadow to Junior Shadow rather than close one post and start a new one, presumably it had been a mistake. Looks like our code assumes a post will never just disappear like this. We should run a check to see if there are any other posts in this situation and delete/mark them as ended appropriately.

**Comment by struan** [comment]
I've added `scripts/check-bad-ministers` and it looks like there are 72 posts where there's a mismatch between the json and the database. I'll look into them next week.

**Comment by struan** [comment]
I've fixed pretty much all of these now apart from two cases where I think it's parliament missing data (Not listing Ed Miliband as leader of the opposition and also not listing Harriet Harman's first stint as Leader). I'll have another check at those tomorrow and probably email Parliament about at least the Ed Miliband one.

**Comment by struan** [comment]
I think these are all fixed now.
