### ISSUE TITLE
MP page wording is inappropriate for MPs who have died.

### ISSUE THREAD

**Issue by Deborah-mySoc** [mysociety/theyworkforyou#121]
Bernie Grant died in 2000.

On his profile page it says things like: 
How Mr Bernie Grant voted on key issues since 2001:

**Comment by MyfanwyNixon** [comment]
This still appears to be an issue - eg see http://www.theyworkforyou.com/mp/14937/lewis_dawnay/thirsk_and_malton. Died in 1910 but it still says 'how he voted since 2001'

**Comment by dracos** [comment]
Subtly different – that issue is that the box shouldn't be appearing at all if there's no information (I don't think it used to display in the old design from what I recall), which is your #734. This issue is that for an MP who does have voting information, it shouldn't be saying "since 2001" if their voting record is from before that… As you say, it does appear to have become an issue again also.

**Comment by tmtmtmtm** [comment]
The box no longer appears — at least in [this case](http://www.theyworkforyou.com/mp/14937/lewis_dawnay/thirsk_and_malton):

![screen shot 2016-02-15 at 08 46 51](https://cloud.githubusercontent.com/assets/57483/13043566/b708b208-d3c0-11e5-8788-f57ae2fdbb20.png)

Please re-ticket if you find other cases.
