### ISSUE TITLE
Add 'recent votes' to voting record on MP page

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#1211]
Show MPs voting record order by date as an option

Part of #1210

**Comment by JenMysoc** [comment]
@paullenz @markcridge this has come up again as an MP has emailed the support to say that the records don't reflect how they've voted because the data hasn't flowed through yet. 

If we move ahead and do stick more recent votes in you both might have some thoughts about what/how/when/where we should do this

**Comment by wrightmartin** [comment]
There's a few options to add this and the relevant controls.

I haven't managed to get TWFY working locally yet, so for now I've focused on the navigation and controls.

Struan has already done most the hard stuff in this PR #1214 

1. We add 'Recent votes' to the main 'person navigation' on the MP page (this is what we have in the PR at the moment)
![artboard copy](https://cloud.githubusercontent.com/assets/2292925/23021214/bd0803d6-f442-11e6-9c80-7b26b5f0b6d2.png)



2. We add a new level of navigation to the person navigation that offers the two views
![artboard](https://cloud.githubusercontent.com/assets/2292925/23021144/5d44b7aa-f442-11e6-8e77-59af5fa6b2b2.png)


3. We turn it into a display control on the vote page itself (I'm not as confident in this, as it feels like there's more going on than a simple reorder of the votes, so this might be the wrong type of control to use and might confuse users)

![artboard 2](https://cloud.githubusercontent.com/assets/2292925/23021155/6cfe017e-f442-11e6-9bc7-5f51d8b403ca.png)

**Comment by struan** [comment]
I think I like the first because it makes it immediately clear that they can see recent votes and there aren't two clicks to get to it. Given that this is aiming to fix the "How do I find out how my MP voted in $recent_vote" I think the more obvious it is the better.

**Comment by struan** [comment]
Also worth noting that there was a design to include this on the front page too: https://github.com/mysociety/theyworkforyou/issues/399

**Comment by zarino** [comment]
I’m not sure how we could _ever_ "sort" the "Voting Record" (`/votes`) page by date – since the things presented on that "Voting Record" page aren’t actually individual votes, but "stances" – ie: average positions on a topic calculated from a number of votes over time.

I guess we could bring topics/stances that contained recent votes near the top, but I still don't think that’ll display what the MPs _want_ us to display, which is: "These are the things I have have done recently in parliament on my constituents’ behalf" … or, for that matter, the thing that users probably want to see, which is: "How did my MP vote on that topic I heard about in the news today?"

More I think about it, the more it feels like a separate page – which means I’m fairly happy with how @struan’s new `/recent` page (https://github.com/mysociety/theyworkforyou/pull/1214) is looking.

I guess in an ideal world, it wouldn't be hidden away *at all*, and would instead be presented as a nice Facebook-style timeline on the MP’s main profile page…

**Comment by wrightmartin** [comment]
> I guess in an ideal world, it wouldn't be hidden away at all, and would instead be presented as a nice Facebook-style timeline on the MP’s main profile page…

Is there budget/desire to add a new block to the main profile page for recent votes, like we did with the postions?

**Comment by zarino** [comment]
@wrightmartin – The budget question is one for @JenMysoc and @mhl I expect, but from my perspective, I think there’s a lot of good we could do in reassessing the layout and content of these MP pages, especially in the eyes of a casual, "cause-based" / "topic-based" visitor.

But in the meantime, can’t see why we don’t just implement recent votes as a separate page for now, and revisit later, maybe, as part of a deeper "let’s make MP pages awesome" exercise.

**Comment by struan** [comment]
This is now live.
