### ISSUE TITLE
JSON decoding problem

### ISSUE THREAD

**Issue by methodds** [mysociety/theyworkforyou#1218]
Hi, 
I'm currently having problems with converting an API response to JSON with Python (dictionaries).

```
import requests
def get_twfy(method, **para):
    '''connecting to the KAS API'''
    url = base + method
    params = dict(para)
    params['key'] = key
    r = requests.get(url, params = params,
                    headers=headers)
    return r


test = get_twfy('getWrans', person=10384, num='1000')
test.status_code
200

test.text[:200]
'{"info":{"s":"speaker:10384 section:wrans","results_per_page":1000,"page":1,"first_result":1,"total_results":54,"spelling_correction":""},"searchdescription":"in the \'Written Answers\' speaker:Lord McF'

test.json()

JSONDecodeError: Expecting ',' delimiter: line 1 column 902 (char 901)
```
The corresponding twfy page can be found [here](https://www.theyworkforyou.com/api/docs/getWrans?date=&search=&person=10384&gid=&year=&order=&page=&num=1000&output=js#output). For some reason, the API does not seem to return perfectly valid JSON.
Can you please help me out here?

**Comment by dracos** [comment]
TWFY is now UTF-8 internally, and if you use `json` as the output type rather than `js` you should get valid JSON back. (This isn't yet documented!) The `js` output was never valid JSON as it was ISO-8859-1 rather than UTF-8, but it looks like we have introduced a bug while trying to maintain backwards compatibility which we'll take a look at. But using `json` should solve your issue and we'll update the docs soon to pretend `js` never existed :)

**Comment by methodds** [comment]
Sorry I'm not sure whether I understand this correctly. Do I have to use an additional parameter in my function call? E.g. ```get_twfy('getWrans', person=10384, num='1000', output='json')```?

**Comment by dracos** [comment]
Yes, that will do it. `output` is an option as described at https://www.theyworkforyou.com/api/ – it defaults to `js`, which I guess we will not be able to change anytime soon as clients will assume that, but you can specify which output you want like that.
I suggest you put it as `params['output'] = 'json'` in `get_twfy` rather than specify it in each call :)

**Comment by methodds** [comment]
Alright, I'll check that. Thank you =)

**Comment by methodds** [comment]
It works, thank you :)
