### ISSUE TITLE
[User request] Remove superfluous fb.com from Facebook profile link on MP profile

### ISSUE THREAD

**Issue by JenMysoc** [mysociety/theyworkforyou#1268]
User has reported the following:

> https://www.theyworkforyou.com/mp/25316/michelle_donelan/chippenham

>  At the above link there is a link to Michelle Donelan’s facebook profile, and the link appears as https://facebook.com/fb.com/MichelleDonelanChippenham which is broken, would you be able to possibly correct it to remove the superfluous fb.com?

You can see this in situ:
![screen shot 2017-05-31 at 12 41 08](https://cloud.githubusercontent.com/assets/4170351/26630482/c88d3e3e-45fe-11e7-9cb8-813188207523.png)

**Comment by tmtmtmtm** [comment]
This is coming from EveryPolitician, which ends up with this value because data.parliament.uk gives the address as `http://fb.com/MichelleDonelanChippenham` rather than `http://facebook.com/MichelleDonelanChippenham` and I was entirely unaware that facebook links _could_ be in that format, so it ends up turning her account name into 'fb.com/MichelleDonelanChippenham', which TWFY presumably simply prepends with a 'facebook.com/' link.

I've [released a new version](https://github.com/everypolitician/facebook_username_extractor/pull/4) of `facebook_username_extractor`, updated EP to use it, and [regenerated the UK data](https://github.com/everypolitician/everypolitician-data/pull/36962).

I'm not sure how or when that data then makes its way into TWFY, though.
