### ISSUE TITLE
GetMP function "Unknown constituency, or no results for that constituency"

### ISSUE THREAD

**Issue by rjgux** [mysociety/theyworkforyou#1269]
Trying to use the API getMP function, whatever postcode/constituency is input, the same error of **"Unknown constituency, or no results for that constituency"** is returned.

On the api/docs page (https://www.theyworkforyou.com/api/docs/getMP) using the explorer I have the same issue, tried a number of different postcodes/constituencies (including 'Aberavon' in the example) and getting the same error.

**Comment by dracos** [comment]
There are no MPs between dissolution and a general election. 
On the page you link to, the `always_return` parameter: "For the postcode and constituency options, sets whether to always try and return an MP, even if the seat is currently vacant (due to e.g. the death of an MP, or the period before an election when there are no MPs)."
https://www.theyworkforyou.com/api/docs/getMPs has a clearer message on this.
