### ISSUE TITLE
db/schema.sql needs bringing up to date

### ISSUE THREAD

**Issue by simonrrr** [mysociety/theyworkforyou#1347]
Creating a new database instance is now impossible on a modern MySQL instance without manually editing schema.sql. 3 issues:

- Default date of '0000-00-00' is no longer allowed (should be '1970-01-01').
- Similarly default date-time of '0000-00-00 00:00:00 is no longer allowed'
- Defaulting a text field to '' is not allowed either

**Comment by dracos** [comment]
Thanks. MySQL added no zero date/times to strict mode in 5.7.4 but rolled it back in 5.7.8 - which version do you mean by "modern"? It looks like 5.7.8 also added no-zero-dates to its default `sql_mode` but you can choose to turn that off (so I'd advise doing so here for the moment, rather than waiting for it to be fixed).
I don't understand default text field to the empty string not being allowed, do you have documentation for that?

**Comment by dracos** [comment]
Ah, I see this has been the case for a while, but it is only an error on Windows, a warning elsewhere? https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql#4553664

**Comment by dracos** [comment]
It looks like both the text defaults (those are the only two I spotted anyway) could be dropped.

**Comment by simonrrr** [comment]
I'm on 5.7.11 on OS X - text defaults are an error here too - will check on sql_mode for no-zero-dates...

**Comment by simonrrr** [comment]
OK - setting sql_mode to '' takes all the errors out - will close (though maybe worth adding to INSTALL.md)

**Comment by dracos** [comment]
Glad to hear it. Sure, feel free to PR :)
The default  <=5.7.4 was `NO_ENGINE_SUBSTITUTION`; it certainly looks like other things added to the default there since may cause problems too with the code as it is, such as `ONLY_FULL_GROUP_BY`.
