### ISSUE TITLE
User suggestion: include more context on the votes in alerts

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#1416]
>When seeing the way my MP voted would be useful were I to know for what they were voting. Would it be possible to either add a single line to say what the bill is about, or even better, provide a link to the preamble to  bill?

Rather than changing the alert emails, one solution may be #1415 - making the full debate easier to find from the actual voting pages.

Adding a link to the debate in the alert may also be desirable?

**Comment by dracos** [comment]
Sadly we don't have any data on what any bill was about, and so we can't provide a link to any bill preamble. Think #1415 best solution at the mo.

**Comment by dracos** [comment]
Just some notes, that can be linked to. The default text of the alert/website for a division automatically imported is something like this (for an MP who voted aye):
```
Finance (No. 3) Bill - Impact of provisions of section 5 on child poverty and equality (8 Jan 2019)
https://www.theyworkforyou.com/divisions/pw-2019-01-08-285-commons
Voted aye (division #285; result was 294 aye, 312 no)
```
Which as complained, means you have to click through, then to the debate, then work out what's going on, in order to know what the vote was about. Note the official site for this division at https://hansard.parliament.uk/Commons/2019-01-08/division/877FFB06-C672-4DFE-ADD2-A3EA16DE1F62/Finance(No3)Bill?outputType=Names does not even get a debate subtitle, which we at least try and get (not 100% correctly, though).

Manually, we can, if time/resource allows, provide descriptions of votes, so e.g. today we actually had the following for that division:

```
Finance (No. 3) Bill - Impact of provisions of section 5 on child poverty and equality (8 Jan 2019)
https://www.theyworkforyou.com/divisions/pw-2019-01-08-285-commons
Voted (aye) to require the Chancellor of the Exchequer to review the
impact of clause 5 on child poverty and equality (division #285; result
was 294 aye, 312 no)
```

Which is quite a lot better (though just pushes it back, e.g. what is "Clause 5", etc etc etc), with the descriptions coming from the Hansard explanatory note on the clause/amendment. But this of course takes time to do, because as far as I can tell there is currently no automated matching between the description of a clause/amendment and its corresponding division. Our code could presumably be improved to try and spot it better, but the source XML (cut down) we get from Hansard is as follows:

```
<hs_2cBillTitle>Finance (No. 3) Bill</hs_2cBillTitle>
<hs_Para><I>Consideration of Bill, as amended in the</I> <I>Committee and</I> <I>the</I> <I>Public Bill Committee</I></hs_Para>
<hs_8Clause>New Clause 1</hs_8Clause>
<hs_7SmCapsHdg>Impact of provisions of section 5 on child poverty and equality</hs_7SmCapsHdg>
<hs_AmendmentLevel1>...</hs_AmendmentLevel1>
...
<hs_AmendmentLevel0><I>This new clause would require the Chancellor of the Exchequer to review the impact of clause 5 on child poverty and equality.</I></hs_AmendmentLevel0>
```
^^^ [MS: This is the description of what is being voted on] ^^^
```
<hs_Para><I>Brought up, and read the First time.</I></hs_Para>
<hs_Timeline>2.53 pm</hs_Timeline>
<hs_Para><Member><B>Peter Dowd</B> (Bootle) (Lab):</Member>I<hs_TimeCode time="2019-01-08T14:50:24"> </hs_TimeCode>beg to move, That the clause be read a Second time.</hs_Para>
<hs_Para><B><Member>Madam Deputy Speaker (Dame Eleanor Laing):</Member></B> With this it will be convenient to discuss new clause 5—<I> Review of public health and poverty effects</I>
—</hs_Para>
<hs_AmendmentLevel1>...
```
^^^ [MS: This *could* be what is being voted on first, perhaps. ] ^^^
```
<hs_Para><B> <Member>Peter Dowd:</Member></B>I<hs_TimeCode time="2019-01-08T14:50:24"> </hs_TimeCode> rise to speak to new clause 1 in my name and that of my right hon. Friend the Leader of the Opposition and other Members.</hs_Para>
...
<hs_Para><I>Question put,</I> That the clause be read a Second time.</hs_Para>
<Division>
<hs_Para><I>The House divided:</I> Ayes <AyesNumber>294</AyesNumber>, Noes <NoesNumber>312</NoesNumber>.</hs_Para>
<hs_Para><B>Division No. </B><B> <Number>285</Number> </B><B>]</B> <Right><B>[</B> <B> <Time>4.52 pm</Time></B></Right></hs_Para>
...
<hs_Para><I>Question accordingly negatived.</I></hs_Para>
</Division>
```
^^^ [MS: Nothing, unless you parse out the "Question put" and deal with amendments to clauses or motions etc, to link this to the description above.] ^^^

With the manual intervention on this division, ours looks quite good: https://www.theyworkforyou.com/divisions/pw-2019-01-08-285-commons
So we can hope to do that on other important ones in future.
