### ISSUE TITLE
Issue relating to division 131 held on Tuesday 13 October 2020

### ISSUE THREAD

**Issue by RichardTaylor** [mysociety/theyworkforyou#1560]
At:

https://www.theyworkforyou.com/debates/?id=2020-10-13b.188.0

Currently the division link has the text: "Division number 0" whereas I would expect "Division 131" in line with:

https://hansard.parliament.uk/Commons/2020-10-13/division/A5057460-5352-4242-9C91-5BE6A6D5381C/BusinessOfTheHouse(Today)?outputType=Names ([Archive link in case the Parliament link doesn't persist](http://web.archive.org/web/20210328181738/https://hansard.parliament.uk/Commons/2020-10-13/division/A5057460-5352-4242-9C91-5BE6A6D5381C/BusinessOfTheHouse%28Today%29?outputType=Names))

Linked to PublicWhip issue: https://github.com/publicwhip/publicwhip/issues/34 where there are more details. 

This combined PublicWhip/TheyWorkForYou issue doesn't have any important consequences I don't think, but there is something wrong here. Currently it's not possible to describe the division on PublicWhip, so no summary of it can be provided to TheyWorkForYou. It doesn't appear likely this division would contribute to any statements made about an MP's voting record.

**Comment by dracos** [comment]
That division number in the source XML was given as `<B>13</B><B>1</B>` which the parser did not spot. Should be fixed by https://github.com/mysociety/parlparse/commit/f9fe550ba0bc4f8f40704938370fe0a053f73109 and I've updated our XML and reimported into TWFY, so that page is now okay. Hopefully that should percolate through to PublicWhip in the next day or two.

**Comment by RichardTaylor** [comment]
Just to note the PublicWhip element of this remains unresolved.
