### ISSUE TITLE
Repeatedly alerting on the same item of future business is annoying to users

### ISSUE THREAD

**Issue by abimysoc** [mysociety/theyworkforyou#1574]
Well, to at least the two who have written to us within the last few weeks to ask for it to be stopped.

In each case they had a `speaker` alert for a particular MP and that MP is due to speak in a debate that's several weeks or months away. They get repeated (daily?) alert emails for it, and with Parliament in recess it may well be the only thing being alerted on.

**Comment by abimysoc** [comment]
A third person has written in, and one of the first two is so annoyed they've decided to annoy us by repeatedly complaining about it, marvellous.

**Comment by dracos** [comment]
I'd unsub that person to fix that one, at least ;)
I did have a look when this first came in, but couldn't see anything obvious. It certainly shouldn't be doing that, and I don't think has been until recently, otherwise we'd have heard about this a long time ago. Nothing should have changed in that part.

**Comment by dracos** [comment]
The DB has timestamps as 15:00:00 and the new data has 15:00 so it is constantly saying they are new and so refreshing them for search results.

**Comment by dracos** [comment]
Okay, this has been fixed.
