### ISSUE TITLE
Update party colours with newer parties

### ISSUE THREAD

**Issue by jacksonj04** [mysociety/theyworkforyou#690]
The existing party colour list hasn't been updated for a while, and doesn't feature colours for current parties of interest (or likely to be of interest in the upcoming election) such as UKIP and Green.

<del>Colour lists are found in two places:</del>

* [_mp.scss:200](https://github.com/mysociety/theyworkforyou/blob/281fb424057adfcec83f1e33928fab6679f7147c/www/docs/style/sass/pages/_mp.scss#L200)
* [<del>member.php:750</del>](https://github.com/mysociety/theyworkforyou/blob/8bf90af677e08d592f48707d3e8c7a939aa02c48/www/includes/easyparliament/member.php#L750)

<del>which probably want bringing in step or re-evaluating to determine if we really need both.</del>

**Comment by zarino** [comment]
The `$party_colours` array was [removed from member.php a while back](https://github.com/mysociety/theyworkforyou/commit/881e190bf564569fa43efd6b2170f0f4821c9b09). So it's just the Sass files that need updating.

The class assigned to those little `span.party` dots is now something like `Labour`, `Conservative`, or `Labour/Co-operative` (which won't be a valid CSS selector, since it contains a slash). So we'll need to [put those into the Sass file](https://github.com/mysociety/theyworkforyou/blob/b3b9a90293bab6665225865161104a8a3a70e658/www/docs/style/sass/pages/_mp.scss#L206-L228), rather than the existing `Lab`, `Con`, etc.

(Fitting the forward slash in `Labour/Co-operative` into a CSS selector will be fun. I think, theoretically, it can be escaped with a backslash. But I've never seen it in the wild which makes me suspicious. We could, alternatively, sanitise the party name classes to something that doesn't need escaping.)

**Comment by struan** [comment]
I would suggest that instead we just put in a tiny bit of logic to make the Labour/Co-operative selector just say Labour.

**Comment by struan** [comment]
Sorry, not selector, class.

**Comment by zarino** [comment]
Pull request with 4 more minority parties here: https://github.com/mysociety/theyworkforyou/pull/957
