### ISSUE TITLE
Page-edge spacing in new design is broken and needs reviewing

### ISSUE THREAD

**Issue by wrightmartin** [mysociety/theyworkforyou#695]
All the outside gutters seem to be implemented in different ways across the new pages, and as a result is inconsistent or just broken in many places. It needs reviewing, this won't be a fun ticket.

**Comment by dracos** [comment]
Links/same as #455

**Comment by zarino** [comment]
This issue affects all "new style" pages: the MP page, debates/wrans pages, the `/alerts/by-postcode` page, and the new homepage in branch [issues/589-new-homepage-design](https://github.com/mysociety/theyworkforyou/tree/issues/589-new-homepage-design).

I've only looked at the MP page in any detail this afternoon, and from what I could tell:

* The header works as expected, with a nice gutter on all window sizes.
* The subnav and the sidebar/content boxes touch the edges of the window once it gets narrow.
  * This is because they're wrapped in `.page-content__row`s which are attempting to counteract the double gutter introduced by the nesting of Foundation `grid-column()`s (the `.sidebar__unit` and `.primary-content__unit` which are both inside a `.full-page__unit`).
  * The correct solution here is probably to remove the `.page-content__row` classes, and move the `.person-panels` div *outside* of the `.full-page__unit` that contains the subnav. That way we don't end up with nested columns, no more double gutters, and thus no need for the negative margins provided by `.page-content__row`.
  * Once you've done that, it all works, apart from the Magellan fixed sidebar on scroll, which currently has a `width` of `16%` – I can't work out what the width *should* be, however. (I thought `13.6666%`, given the sidebar’s normal width of `16.6666%` minus `1.5%` padding on each side – but that doesn't look right when you try it).

**Comment by wrightmartin** [comment]
Is the sidebar padding ```1.5%``` of the full page row width, or the sidebar width? If it's the sidebar width you need to switch up the context. Without trying it, here's the figures:

```1140px``` is our canvas, and ```34px``` is the gutter we're aiming for (```~3%```). 

Sidebar width is ```190px``` (```16.6666%```), so ```34px``` is ```17.894736842%``` of that giving a left and right padding of ```8.947368421%``` on the sidebar

**Comment by zarino** [comment]
@wrightmartin – As it turns out, the problem was elsewhere: elements with `position: fixed` are sized relative to the viewport, not their parent. Which explains why the sidebar had that [suspicious hard-coded `max-width`](https://github.com/mysociety/theyworkforyou/blob/742b40d54a31db493b2ab6a49a321649d06ae898/www/docs/style/sass/pages/_mp.scss#L294) – it's there to stop the sidebar maintaining its 16.666% width (or 13.666% excluding padding) once the viewport is wider than the page (1140px).

Anyway, it's all sorted out in 056727af3abdccb9467a90f1ba8b73b6b291af64, most notably by these lines: https://github.com/mysociety/theyworkforyou/blob/056727af3abdccb9467a90f1ba8b73b6b291af64/www/docs/style/sass/pages/_mp.scss#L293-L303

**Comment by wrightmartin** [comment]
@zarino ah, yeah, that lovely feature.

Well done. Also, why had I never come across ```strip-unit()``` before? Handy!

**Comment by zarino** [comment]
Yeah, `strip-unit` is, astonishingly, not a Sass builtin, but something provided by Foundation. It's annoying that I have to use it *at all* in this case (since I'm just telling Sass to give me `X%` of `1140px`) but I guess the concept of "a percentage" is different in Sass (where it might be a unit of measurement, rather than a fraction) so I have to explicitly convert it to a fraction and multiply that way. Sigh.

**Comment by zarino** [comment]
Pull request here: https://github.com/mysociety/theyworkforyou/pull/866
