### ISSUE TITLE
User suggestion: include some alliterative phrases

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#740]
"She sells seashells: I have never used the website before, and although I found the rest of it VERY helpful indeed, I found this statistic peculiarly unhelpful... I read what you had to say about it, and wondered why you don't give us examples of what is actually said. You simply leave it mysterious.
If you have the data, and your machines can count how many such phrases are used, why not go the extra mile ( as they say!) and ask the machines to take a sample of say 20 of the three word phrases that a particular MP used, and tell us what they are?
Otherwise the statistic is not meaningless, but deeply uninteresting.
I am sure MPs would be interested in seeing their quirky/repetitive turns of phrase, too!"

**Comment by dracos** [comment]
We do store the content, and it's available in the API as `three_word_alliteration_content`, but it's not shown because, well, here's some sample from my MP: `:are available as:to treat them:the travelling time:that the then:thanks to the:to take them:the teeth that:that the taxation:who work with:today that the:he has had:to take those:true that the`.
