### ISSUE TITLE
Decide what to do about SP WRANS mentions

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#745]
They either need a bit of design love or, as it's old data that's not going to be updated now possibly just removed.

See http://www.theyworkforyou.com/spwrans/?id=2011-03-17.S3W-40354.h for an example.

**Comment by zarino** [comment]
Eg:

![screen shot 2015-04-14 at 12 12 49](https://cloud.githubusercontent.com/assets/739624/7135539/b04ada62-e29f-11e4-9235-643e0a01276c.png)

**Comment by dracos** [comment]
On one such as http://www.theyworkforyou.com/spwrans/?id=2011-03-17.S3O-13323.h there are spacing issues between the sidebar and main content also, due to the sidebar being position absolute.
(And I realise this isn't the same thing, but if the fix for this does also fix the sidebar issue of e.g. http://www.theyworkforyou.com/pbc/2014-15/National_Health_Service_%28Amended_Duties_and_Powers%29_Bill/06-0_2015-03-03a.2.0 that'd be good :) )
