### ISSUE TITLE
Division results design should be looked at

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#746]
I did a bit of work on the list of Yeas and Nays in division results but a quick glance over from a designer to check/advice would be good.

Example at http://www.theyworkforyou.com/debates/?id=2015-02-03e.160.0#g187.0

**Comment by zarino** [comment]
A few things I noticed this morning, while looking at the controversial "do we bomb Syria?" division:

MP names get wrapped, haphazardly, onto multiple lines. Makes it really card to scan the list because you have to guess where one name ends and another starts.

![screen shot 2015-12-03 at 10 19 52](https://cloud.githubusercontent.com/assets/739624/11557975/be172dca-99a7-11e5-8823-9ae3b0e605b3.png)

I have a feeling, since we *always* know there will be a binary vote, the simplest layout would be two columns, one for Aye, one for No, with MPs listed vertically and alphabetically. Not only does it bypass the line-wrapping (two columns of names rather than four) but it lets you instantly see, just from the length of the two columns, which side had the most votes.

We append "(teller)" to some of the MPs’ names, but we don't explain what "teller" means or why we’re pointing out.

![screen shot 2015-12-03 at 10 06 37](https://cloud.githubusercontent.com/assets/739624/11557701/fa461830-99a5-11e5-9a09-a7ddb4e2487c.png)

It's a seriously long page, and the vote is hidden at the bottom. Adding a button near the top for "Just jump to the vote" would help people (like me!) who just want to see who voted which way.

**Comment by zarino** [comment]
See also https://github.com/mysociety/theyworkforyou/issues/43 for an old suggestion of how we could visually represent the party split in votes like this, which would be an interesting addition to the wordy division list.

**Comment by zarino** [comment]
How about this as a starter for ten? Would love to get your feedback, @wrightmartin @struan @dracos:

![iteration-1](https://user-images.githubusercontent.com/739624/38990135-ff1fce46-43d0-11e8-8d2c-3dc815f07de7.png)

Things this does:

* Pulls in the title and subtitle of the section (from the page header) to remind you roughly what the division is about – it’d be nicer to pull in the opening "statement" that actually describes the subject of the debate, but I don’t think that’s easy for us to pick out.
* Shows how _your MP voted_ if you have set a postcode, and your postcode’s _current MP_ participated in the division. We re-use the same pale yellow treatment from the "Your MP" section of `/mps` for some consistency.
* Visual representation of division, by Aye/No and by party – the two biggies that everyone wanted. Votes are grouped into 5×5 blocks so they’re easier to count.
* Two, single-column voter lists – if JavaScript is enabled, we visually truncate the lists to the first 10 or so MPs. (I’m not convinced about this – it keeps the layout clean and makes an already super lengthy page slightly shorter, **but** it’ll break Cmd-F / Ctrl-F / "Find in page" if someone wants to search for an MP by name.)

Things this does not do:

* Give Tellers any special treatment, or even explain what a Teller is.

**Comment by dracos** [comment]
Just to note the current voting lists are static HTML created on import, it's not db-generated, see generation at https://github.com/mysociety/theyworkforyou/blob/master/scripts/xml2db.pl#L1026 . So ideally this would involve changing that to either store 'data' in the speech that the front end can then parse out/convert for display, or even store the data in its own database table (policydivisions already exists, so divisions is only a reuse of that, potentially...), or at least changing that format. Regardless of which, it would mean reimporting debates to have old ones updated.

As for the design, I like it apart from the title - if there are multiple divisions (e.g. quite common to have two straight after one another, one on an amendment, another on the resultant clause), both looking identical because of the title would be more confusing than no title I think; especially if it makes it look like a vote on (in your example) the EU Protocol on sentience, when it might be the opposite.

"it’ll break Cmd-F / Ctrl-F" - font size getting smaller and smaller, with some magic way of making it bigger again when you're near it?

**Comment by struan** [comment]
This is lovely.

It'd be nice I think to give some indication of how many MPs didn't vote although that's a bit trickier in some ways.

And yeah, as matthew says vote titles can be a bit problematic.

**Comment by wrightmartin** [comment]
I like the design generally. Just wondering about the infographic - could we vary the shape of the marker as well as the colour? That way it might make it a bit more robust for colour-blindness or hard of sight users.

**Comment by struan** [comment]
We should also update the individual division result pages as well, e.g:

https://www.theyworkforyou.com/divisions/pw-2018-01-16-95-commons

These are only for votes that are part of a policy but applying the same design to them would be nice.
