### ISSUE TITLE
Make new streamlined MP alert sign up page

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#800]
Very simplified enter postcode and signup button page for use in email campaigns encouraging people to sign up to their MP post election.

@zarino to do HTML layout and styling (using the same base template as the new MP and Debates pages) then @struan or @dracos to implement it in the TWFY code.

**Comment by TomSteinberg** [comment]
The goal here is to have a 'sign up to your new MP for alerts' page that can be put in the email newsletter, into twitter and so on

**Comment by TomSteinberg** [comment]
@MyfanwyNixon for interest and preparation - its in the grid now, maybe consider a newsletter for the day after the election?

**Comment by MyfanwyNixon** [comment]
Nice!

**Comment by jacksonj04** [comment]
Could someone ping me once this is almost ready to go, so I can get tracking set up?

**Comment by dracos** [comment]
Design wise, this is a page that performs the same functionality as http://www.theyworkforyou.com/alert/ but solely asking for postcode (and email address if not logged in), and with presumably a lot less gumph, and also presumably in the new design. Technologically, it will then take you directly to be signed up/email confirmation, rather than the annoying intermediary step that http://www.theyworkforyou.com/alert/ does when given a postcode (and if this page can use the same code as http://www.theyworkforyou.com/alert/ and we can fix that at the same time, great). It would be good if the design could in some way be usable for the more general http://www.theyworkforyou.com/alert/ in future too.

**Comment by zarino** [comment]
Pull request for the design work here: https://github.com/mysociety/theyworkforyou/pull/818

**Comment by MyfanwyNixon** [comment]
Please also ping me when this is live so that I can put the link into the newsletter & blog post.
