### ISSUE TITLE
Image wording contrasts with MP's stance

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#806]
When an MP has voted strongly or moderately against a policy, we could consider displaying images with wording reflecting this.

For example:
http://www.theyworkforyou.com/mp/24900/simon_kirby/brighton%2C_kemptown/divisions?policy=6674
The image states 'someone who voted for this', while my MP voted strongly against it. 
It's a small point but my first inclination is that it's confusing for the wording in the image not to match the stance below.

**Comment by MyfanwyNixon** [comment]
And even more so on pages like http://www.theyworkforyou.com/mp/11545/edward_miliband/doncaster_north/divisions?policy=1136 which actually contains the word 'for' ("Reducing the number of MPs - for"), although the MP was against.

**Comment by RichardTaylor** [comment]
I agree. I think it would be better if the most prominent text, the text on the image, was the sentence on the MP's voting record eg. 
> Edward Miliband voted moderately against fewer MPs in the House of Commons 

I think the pages would be better without the policy titles and descriptions at the moment. 

Given the detail provided by lines on each vote I don't think they're needed.

**Comment by RichardTaylor** [comment]
There are already neutral titles and descriptions in the spreadsheet:

https://docs.google.com/a/mysociety.org/spreadsheets/d/1x-lYhCO4FzQvqu1EV1NioapppOpM0fcVafKzBEFvGBg/edit?usp=sharing

I've just been through them to trim some down; but they might need a bit more height in the image to accommodate them.

PublicWhip titles and descriptions have to be "directional" as they're what the votes are being compared against so unfortunately we can't just neutralise the PublicWhip titles and descriptions and then use those. There's also an issue of the length of PublicWhip titles and descriptions being, arbitrarily, very limited and the fact they've been written for a bit of a different purpose - with more of a focus on setting criteria for a vote to be included in a policy or not rather than explaining what a policy covers to a TheyWorkForYou user. 

So I now think - try it with the neutral titles and descriptions - as well as perhaps emphasising the sentence on the MP's voting record a bit more.

**Comment by struan** [comment]
Ah, at the moment the code uses the descriptions from PublicWhip rather than those from the spreadsheet. I'll make some changes to reverse that and then update the descriptions on the site.
