### ISSUE TITLE
Use UTF-8 charset in new HTML pages

### ISSUE THREAD

**Issue by zarino** [mysociety/theyworkforyou#815]
This would probably incur significant developer time, but it feels like 2015 is the year TheyWorkForYou pages should get served with a UTF-8 content-type. (They're currently served as `iso-8859-1`.)

I mention it because earlier today I typed a curly quote into a TWFY template, and I got gobbledegook out of the browser, and it felt like I was back in 2005. Replacing every unicode character with HTML entities is all well and good, but I can't recall the last time I had to do it in any other mySociety product.

Feel free to `wontfix` if this isn't a priority, but @jacksonj04 said I should vent somewhere ;-)

**Comment by dracos** [comment]
2017? What needs to happen:

- [ ] Names and constituencies are stored/output as ISO-8859-1, they need to be stored as UTF-8.
- [ ] The site needs to say it is UTF-8, not ISO-8859-1.
- [ ] Whilst the speech data should be ASCII, a few (0.06%) of entries contain non-ASCII. In most cases, this is actually UTF-8 and so is currently outputting incorrectly (e.g. October 1981 written answers, or unknown speaker names in historic/SP debates). The only thing that appears to currently be outputting non-ASCII ISO-8859-1 characters are division MP names in old Public Bill committees.

**Comment by struan** [comment]
Is this likely to cause issues with API users who are currently expecting ISO-8859-1? Presumably not really for historical content but if we start storing new things as and outputting UTF-8 to them then I expect breakages.

**Comment by jacksonj04** [comment]
We could just use `Accept-Encoding` and expect clients to be well behaved?

**Comment by dracos** [comment]
@jacksonj04 Accept-Encoding is for gzip etc compression, it's the Accept-Charset header for charset, or Accept for Content-Type. But no, I don't think we can just use any of them, because we are using a query parameter to select format so no-one would expect to have to use such headers, nothing to do with them being well-behaved, and so we would have to mandate that any new users have to specify such a header to get UTF-8, which would be the opposite of what we would want.

@struan Yeah, I suggest we add 'json' output to the API (and only document that once it's live), but still accept 'js' and have that continue to output ISO-8859-1 transcoded at output. That should be fine, then. XML we can change the header and assume XML readers will cope, they should be taking account of that.

**Comment by struan** [comment]
> a few (0.06%) of entries contain non-ASCII

How did you work this out? I assume something like this:

http://stackoverflow.com/questions/401771/how-can-i-find-non-ascii-characters-in-mysql#11741314

**Comment by dracos** [comment]
I did `body REGEXP CONCAT('[', CHAR(128), '-', CHAR(255), ']')` :)
