### ISSUE TITLE
User comment on voting line for proportional representation

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#858]
"Thanks very much for providing this site, but I’d like to suggest a change to one part of it, which is a bit misleading (I’m sure unintentionally). 

"In voting records for MPs the site includes for or against a more proportional system for electing MPs. There has never been a vote in the UK parliament on a more proportional system (i.e any form of proportional representation). The vote on the 2011 Alternative Vote Referendum was for AV, which ,as the Electoral Reform Society points out,  is not a form of PR, but a slightly modified version of First Past the Post, in which voters can rank candidates 1,2,3 etc, with the first candidate to get more than 50% of the votes during counting being elected. This still means up to 49.99% of all votes in every constituency do not count and elect no one.

"So it’s misleading to say that MPs who voted for the Alternative Vote voted in favour of a more proportional electoral system. The most that can be said is that they voted in favour of reforming the voting system/ electoral reform."

**Comment by RichardTaylor** [comment]
>There has never been a vote in the UK parliament on a more proportional system
There was a vote in 2010 on expanding the choices to be presented in the referendum to include options which would be expected to result in more proportional representation; and the intent was stated as being to include: "a choice that includes a genuinely proportional system":  

http://www.publicwhip.org.uk/division.php?date=2010-10-12&number=68&dmp=1084

That is the only vote with a "strong" weighting used to calculate an MPs stance on "a more proportional system for electing MPs". 

The rationale is that the existence of that vote justifies including the line on proportional representation in TheyWorkForYou's coverage.

Looking back at it now it's not so clear cut because the vote is about including questions in a referendum and an MP who is either for or against a proposal might still support holding a referendum on it. A good argument can be made here though that a vote for expanding the referendum questions was a vote in favour of more proportional representation. 

The next question is if it's reasonable to see a move away from first past the post to the "alternative vote" or "single transferable vote" as a potential step towards a more proportionally representative system even if it alone doesn't produce proportional representation.  The inclusion of the additional three minor votes is on the basis that is a reasonable thing to say.

http://www.publicwhip.org.uk/policy.php?id=1084

The question asked in relation to each vote is ~"How would an MP who wanted a more proportional system for electing MPs have voted".  

Historically on PublicWhip there were forum threads where discussions on taking specific votes into account when determining particular statements in relation to a particular statement could be publicly recorded. Defending, and explaining, why the decisions which have been made were made would be easier if the rationale had been publicly logged. 

In this case the person who wrote in made a very reasonable point; the response really is that judgements were made that it was appropriate to take a different view. 

I see on PublicWhip there is a policy on just holding the AV referendum or not, which does more closely match what was literally voted on, but perhaps isn't as useful to a reader trying to determine their MPs stances on various policies:

http://www.publicwhip.org.uk/policy.php?id=1112

I don't think there's anything indefensibly misleading being shown; but decisions could have been made differently.

**Comment by tmtmtmtm** [comment]
Are we e
