### ISSUE TITLE
Clean up styling of alerts pages

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#929]
![theyworkforyou email alerts - theyworkforyou 20150803](https://cloud.githubusercontent.com/assets/739624/9036261/c9f2ab72-39d7-11e5-9a05-e1c46fbec184.png)

**Comment by zarino** [comment]
Coding done in https://github.com/mysociety/theyworkforyou/commits/issues/%23929-new-alert-design – just needs HTML + CSS to match the rest of the (new) site.

**Comment by zarino** [comment]
@struan – this ticket was added to the design backlog, but it looks to me like the work has already been done – the alert page *does* already have the new style header and footer.

![screen shot 2015-08-03 at 15 12 00](https://cloud.githubusercontent.com/assets/739624/9039227/f7a264d0-39f1-11e5-81c1-12992017e4e3.png)

Was the ticket added because you think the *content* of the page needs work?

**Comment by struan** [comment]
Yes, the content needs some styling.

Specifically there's a chunk of possible things this page can display in the following conditions:

- Search for a term that matches more than one MP
- Search for a term that matches a constituency
- Search for a postcode
- Search for a postcode and a word
- Use a search that includes a comma
- Visit the page when logged in and you do not have an alert for your current MP
- Visit the page when logged in and you have existing alerts in which case the right hand column has alert management options.

I don't think it needs much other than a bit of tidying, although the last one is not good at the moment.
