### ISSUE TITLE
Email updates

### ISSUE THREAD

**Issue by MyfanwyNixon** [mysociety/theyworkforyou#950]
http://www.theyworkforyou.com/user/?pg=edit includes the option:
> Do you wish to receive occasional update emails about TheyWorkForYou.com?

- [x] @jacksonj04 please can you tell me how many people have signed up for this over the years?
- [x] If a reasonable number, I'll temporarily import them to Mailchimp and send out a newsletter summarising the recent improvements to the site
- [ ] Beyond that, it seems more sensible to change the wording on this page to invite people to receive the general mySociety newsletter, which is the most reliable source of updates about TWFY: "Do you wish to receive occasional update emails about mySociety projects including TheyWorkForYou?"

For discussion: is the wording loose enough that we could in all conscience sign existing TWFY subscribers up to the wider newsletter anyway?

**Comment by jacksonj04** [comment]
@MyfanwyNixon:

* There are **18,193** people who have opted in to TWFY email updates.
* This is a number that almost certainly wants importing into MailChimp and zapping an update.

I'm not convinced that we could maintain a clear conscience by moving them wholesale into the mySociety newsletter list. What might be a good way round (FSVO "good") is adding a 're-opt-in' blurb to the tail of the TWFY update, telling them to go sign up for the general mySociety newsletter if they want updates. My main reasoning for this is because TWFY updates have been very far between, so we'd be suddenly moving people to a significantly higher volume mailing list (although still pretty lightweight in real terms).

**Comment by MyfanwyNixon** [comment]
Thanks Nick, that's very useful. Gosh that is a lot of people! 
If you could give me a csv with name and email address (or just email address if that's not possible) I can import them into Mailchimp and send a mail-out, along with the other sign-up option as you suggest.

**Comment by MyfanwyNixon** [comment]
Abi suggests that "change the wording on this page to invite people to receive the general mySociety newsletter" would be better as "embed the Mailchimp sign-up form" which, yes, easier.

**Comment by jacksonj04** [comment]
:+1:

**Comment by MyfanwyNixon** [comment]
I'll open a new ticket with that last action.
