### ISSUE TITLE
Gay marriage policy always listed as not enough information

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#961]
For all MPs we always say we don't have enough information to decide their position on gay marriage - policy 6686, e.g. http://www.theyworkforyou.com/mp/10780/gregory_campbell/east_londonderry/divisions?policy=6686

**Comment by MyfanwyNixon** [comment]
> A friend has just e-mailed, in some amazement, to say that he has seen the re-designed website and the entry for me, which includes:
 
> ‘We don’t have enough information to calculate Lord Norton of Louth’s position on equal gay rights.’
 
> If you don’t have enough information to calculate my position, then your methodology is up the spout.

**Comment by MyfanwyNixon** [comment]
https://twitter.com/LewisHart17/status/654800280341516293

**Comment by dracos** [comment]
All people mentioned (and everyone else) now have a position.

**Comment by RichardTaylor** [comment]
Thanks for this fix. Just to note the issue was broader than one policy.

Now on [Gordon Brown's page](http://www.theyworkforyou.com/mp/10068/gordon_brown/kirkcaldy_and_cowdenbeath/votes) there's only one "We don’t have enough information" line compared with eight that were there before the fix. (The one that's still there is fine)

Excerpt of Google Cache snapshot from 13 Oct 2015 

<img width="1143" alt="screen shot 2015-10-27 at 16 19 16" src="https://cloud.githubusercontent.com/assets/547695/10764702/4722ed28-7cc7-11e5-81d9-7e6ed686c246.png">
