### ISSUE TITLE
Put back search help

### ISSUE THREAD

**Issue by struan** [mysociety/theyworkforyou#983]
In the redesign the quick help for the search was removed and we should add it back to prevent people emailing support.

**Comment by zarino** [comment]
There was talk of adding these search tips back into the sidebar, but I’m worried people won’t see them when they need them. Especially since the tips are quite verbose, so will be very easy to ignore as a big block of uninteresting text.

![screen shot 2015-09-30 at 16 10 06](https://cloud.githubusercontent.com/assets/739624/10197055/c158efa6-678d-11e5-8f0c-47f0e2a2b3b7.png)

From the sound of it, when users have contacted support about this, it's been because they want to find a specific phrase. I wonder whether a link, named exactly like that, near to the search input would be easier to spot?

![screen shot 2015-09-30 at 16 05 44](https://cloud.githubusercontent.com/assets/739624/10196958/5e7e216c-678d-11e5-9abd-e7241d0f8590.png)

Clicking it could unfold a little section explaining the search stemming / quoting tips, just like clicking "Advanced search" unfolds a section with extra inputs.

Thoughts, @struan @dracos?

**Comment by abimysoc** [comment]
Can we explain in pictures? http://www.makeuseof.com/tag/become-better-at-finding-stuff-with-search-engines-boolean-search-logic-explained/

**Comment by dracos** [comment]
The old text wasn't that, it was as follows:
<hr>
* TheyWorkForYou search is case-insensitive, and tries to match all the search terms within a document.
* To search for a person, just enter their name &ndash; we will search our database of people, as well as searching speeches made by that person, or that mention that person.
* To search for an exact phrase, use quotes (""). For example to find only documents contain the exact phrase "Hutton Report":<br>
`"hutton report"`<br>
Put a word in quotes if you don't want to perform stemming (where e.g. searching for `horse` will also return results with `horses`).
* To exclude a word from your search, put a minus ("-") sign in front,
for example to find documents containing the word "representation" but not the word "taxation":<br>
`representation -taxation`<br>
* If you want to search for words only when they're used near each other in the text, use "NEAR". For example, to find documents containing the word "elephant" near the word "room":<br>
`elephant NEAR room`<br>
* <strong>Advanced Users:</strong> You can perform boolean searches, with brackets, AND, OR, and XOR. The filters can be entered directly, as well as from the advanced search form, here's a selection:
  * column:123
  * party:Lab
  * department:Defence
  * section:uk section:wms
  * date:20080716
  * 20080101..20080131

<hr>

If we can't come up with something that looks nice (surely you can have something slightly nicer than a block of text, the old design at least had bullet points! :) ), I'm not sure I mind if people don't see them when they need them, because that will be no worse than the current situation; currently, the number of people who can discover this is zero, and if it is there it can only be the same, or better. And if people still email, you can at least point them to documentation they could theoretically have seen, rather than the current impossibility.

There are many different things they could be wanting, of which a specific phrase is only one. The example I quoted elsewhere wasn't actually about searching for a specific phrase, but about stopping stemming on a specific word. I doubt very much that such a link be useful to the majority of users (why do I have a "specific phrase" link for a search for the word "Trident", I don't know what that would mean?), so I think it would be confusing to have a special link like this in some way.

**Comment by wrightmartin** [comment]
- I don't think this should be on the standard search page. Experience tells us that the vast majority of users will use this like Google and be happy, as that is all they expect. Adding more instructions and features is adding unnecessary complexity that doesn't benefit many people, in fact, it clutters up this page with irrelevance.
- Is this not at home under 'advanced search' as an information panel? - this is **advanced** functionality if ever I've seen it, and I'd expect advanced users to be able to find it
- We should enlist the help of @MyfanwyNixon to give the instructions a once over here with brevity and clarity in mind

Hiding these features may feel bad, but I believe the minority who find them useful will find them under 'advanced'.

**Comment by dracos** [comment]
Yes, as long as they exist somewhere that can be pointed to, I don't mind where, that's fine :) Panel under advanced search sounds good.

The only bit I might ask for an exception is the stemming behaviour, as that is the only one of those for which you might want to immediately go from a results page ("hmm, it gave me cycling and cycles when I only wanted cycling"). I think the code could tell whether it had done a search involving stemmed words (e.g. it could know it was performing a stemming search), but I don't think it could know whether that was going to return any stemmed results (even if it went through the page and looked at those and they all only contained the exact searched terms, perhaps further pages would not). Zarino in IRC suggested "we have included words similar to your search term - search only for exact matches" or somesuch, which I think if wasn't too prominent could work if it was shown for any non-phrase search?

**Comment by zarino** [comment]
Sorry to make this little request into a such a saga, but given the traffic the search page gets, it would be a shame not to spend some time making sure we're adding the right things for the right reasons.

Here's a bunch of thoughts I had earlier today, before and during talking to @dracos:

> TheyWorkForYou search is case-insensitive

Do we need to tell them this? Does Google tell its users? Does FixMyStreet or WriteToThem?

> and tries to match all the search terms within a document

What does this actually mean? I searched for `hutton report` and I got pages including only `hutton` or only `report` as the fourth, fifth, and sixth results – that doesn't sound like it's trying very hard to "match all the terms". So maybe it means something else?

> To search for a person, just enter their name – we will search our database of people, as well as searching speeches made by that person, or that mention that person.

Is this here to tell people they can search for people's names (surely not?) or to explain why, when you search for someone's name, lots of other apparently unrelated results, like speeches by other people, turn up?

If it's the former, can we maybe suggest people searching by using the placeholder text in the search inputs themselves? eg: "Find a phrase or person"

> To search for an exact phrase, use quotes (""). 

Are people not used to this already from search engines like Google?

> Put a word in quotes if you don't want to perform stemming (where e.g. searching for `horse` will also return results with `horses`).

As I just discussed in IRC with @dracos, stemming feels like a thing we only need to bring to people's attention when it's actually been applied to their search term. So, *if* I've searched for a word, and *if* TWFY has automatically included other variations of that word, it makes sense to show a "BTW we've included variations of your search term, click here to try without" message. Because that's the point at which I'll be looking at the screen, cursing because all the results are too vague.

> To exclude a word from your search, put a minus ("-") sign in front

You mean just like Google, Amazon, ebay, and almost every other search system out there?

> If you want to search for words only when they're used near each other in the text, use "NEAR"
> Advanced Users: You can perform boolean searches, with brackets, AND, OR, and XOR

This feels a bit like we're taking people on a CompSci 101 crash course. Thankfully it's only a few words, but it simply being there makes me question the reliability of the standard search. Like, if there are "AND" and "OR" operators, what does a space do in a normal search? AND or OR? And if there's a "NEAR" operator, why isn't that the default. When would I want to search for two words that aren't near each other?

> The filters can be entered directly, as well as from the advanced search form, here's a selection…

Can we see how many people do this? From logs or something?

**Comment by wrightmartin** [comment]
>  Zarino in IRC suggested "we have included words similar to your search term - search only for exact matches" or somesuch, which I think if wasn't too prominent could work if it was shown for any non-phrase search?

A contextual message sounds like a fine solution here

**Comment by wrightmartin** [comment]
> Are people not used to this already from search engines like Google?

No, they almost definitely are not

**Comment by dracos** [comment]
I assumed the text would be looked at by Myf as mentioned above, so I'm not bothered about precise wording. I would drop the text you suggest is superfluous, sure. The point is to just have *something* to point at, it's easy to change in future, but currently there is nothing. I consider that more important than having it be amazingly brilliantly perfect off bat. No-one bothered to *complain* about it on the old site ;)

"I searched for hutton report and I got pages including only hutton or only report as the fourth, fifth, and sixth results" - every result you got included both those terms, though presumably not always in the highlighted section. I don't know of a common search engine that shows you more than the first match (and ones nearby if any) it finds in a document? As you say, we behave similarly to search engines, so explaining this is needless.

"TheyWorkForYou search is case-insensitive" - not actually true anyway, as capital letter will prevent stemming.

"If it's the former, can we maybe suggest people searching by using the placeholder text in the search inputs themselves?" - the old design said "a *word*, *phrase*, *person*, or *postcode*". The current design allegedly has "Enter a keyword, phrase, or person" but JavaScript replaces this with "Type a search term and press Enter". I agree the placeholder could certainly be better.

"Like, if there are "AND" and "OR" operators, what does a space do in a normal search?" - AND, as per the bit of text you quoted previously. But if you want to use brackets, you may want this. As I say above, having this under advanced search sounds fine to me, but I don't see why we wouldn't want to at least document the capabilities for people who wish to use it *somewhere*.

"When would I want to search for two words that aren't near each other?" - I would find it very odd for a search to only do that, certainly no common search engine I can think of does that.

"Can we see how many people do this?" - Given this text doesn't exist on the site at present, so no-one knows about it, no, not really :)

**Comment by zarino** [comment]
> The point is to just have something to point at

Right, so after I posted my last message I realised maybe I'm completely misunderstanding the use case for this information. Maybe it's not actually there to help people search. It's there for us to direct people to when they complain that search isn't doing what they expected, or is missing a feature.

If that's the case, then it feels like an FAQ page to me. Especially the stuff that's telling you how the search engine works.

**Comment by dracos** [comment]
Aside, the github advanced search, whereby it autofills the main search box with the correct way of using it when you fill in one of the advanced search boxes, is quite nice.

**Comment by zarino** [comment]
Taking a lead from Google's Advanced Search page, I wonder whether we could work the most common modifiers into the "Advanced Search" form, *alongside* a description of how to use them in plain text?

![screen shot 2015-10-01 at 15 00 43](https://cloud.githubusercontent.com/assets/739624/10222709/5659e0f0-684d-11e5-94f8-9881092cea0c.png)

When you fill in, say, the "Excluding these words" box, it could update the main text box at the top with your word prefixed by a minus sign, appended onto whatever was in there before. Maybe?

**Comment by dracos** [comment]
That looks great :)

**Comment by zarino** [comment]
@dracos If we did something like the separate "excluding these words" boxes, does that also have to work without javascript? Might need some clever server-side work from you or @struan, to manipulate the separate inputs into one.

**Comment by dracos** [comment]
There used to be an exclude parameter, that already works, e.g. http://www.theyworkforyou.com/search/?q=elephant&exclude=room

**Comment by dracos** [comment]
And `phrase` already exists for phrase search: http://www.theyworkforyou.com/search/?q=elephant&phrase=in+the+room
(Looks like the advanced search used to have these boxes, removed by me in f96eaff8f4e59dca44ac49e826a32b18302d9e7c in 2009.

**Comment by zarino** [comment]
Pull request for the "exactly matching" and "excluding" boxes here: https://github.com/mysociety/theyworkforyou/pull/995

Things it doesn't do:

* Explain about the boolean operators (although there's a link to an FAQ section about searching, that maybe @dracos or @MyfanwyNixon could word nice and clearly?)
* Explain about case-insensitivity or searching for people's names. But I get the feeling maybe we're coming round to the idea that they're not really necessary anyway?
* Show you a Github-like all-text representation of your "advanced search" parameters in the main search box. Maybe we might want a new ticket for that? Or is it a bit of a pipe dream?

**Comment by MyfanwyNixon** [comment]
Just to confirm: all that is now needed is an FAQ entry explaining some simple precepts of Boolean search? If so I can polish something up today (and then perhaps @dracos can check it for accuracy).

**Comment by zarino** [comment]
@MyfanwyNixon yes, although it might not need to be much different to the original text (see [matthew’s comment above](https://github.com/mysociety/theyworkforyou/issues/983#issuecomment-144722536)), since it's a few clicks away from the beaten path.

**Comment by MyfanwyNixon** [comment]
Here y'go then:
https://docs.google.com/document/d/18qv-LtZ8anKk0rxxsZTAJFlW44iaIE6RKKYoDCZF2sw/edit

**Comment by zarino** [comment]
Cool. @dracos could you help @MyfanwyNixon out with some examples for the filters at the end of the document?
